apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: ebs-wordpress-pv-claim

spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-sc 
  resources:
    requests:
      storage: 2Gi
  