apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
spec:
  selector:
    matchLabels:
      app: wordpress-db
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
      - name: wordpress-db
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        ports:
          - name: mysql-port
            containerPort: 3306
        resources:
          limits:
            cpu: 1
            memory: 1Gi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-password
        volumeMounts: # Mounting Volume
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
      volumes: # Creating Volume
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: ebs-wordpress-pv-claim
