apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: backend-restapp
  labels: 
#    app: backend-restapp
    tier: backend 
spec: 
  replicas: 03
  selector: 
    matchLabels:
      app: backend-restapp
  template: 
    metadata:
      labels:
        app: backend-restapp
    spec:
      containers:
        - name: backend-rest-container
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: my-backend-service
  labels:
    app: backend-restapp
    tier: backend
spec:
  #type: backend-clusterip-service
  selector:
    app: backend-restapp 
  ports:
    - name: http
      port: 8080
      targetPort: 8080 