apiVersion: v1
kind: Pod
metadata:
 name: nginx2
 labels:
  app: nginx-frontend
spec:
 containers:
 - name: nginx2
   image: nginx
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx2-service
spec:
 type: NodePort
 selector:
  app: nginx-frontend
 ports:
  - port: 80