apiVersion: v1
kind: Service
metadata:
  name: my-backend-service # Must Match with App Settings
  labels: 
    tier: backend
    app: backend-restapp
spec:
  #type: Cluster IP is default service so we dont need to mention.
  selector:
    app: backend-restapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
