apiVersion: v1
kind: Service 
metadata:
  name: httpd-service
  labels:
    app: fronend-httpd-service
spec:
  selector:
    app: fronend-httpd
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
