apiVersion: v1
kind: Pod 
metadata:
  name: tomcat-server
  labels:
    app: frontend-tomcat
spec:
  containers:
    - name: tomcat-server
      image: tomcat
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: frontend-tomcat-service
spec:
  selector:
    app: frontend-tomcat
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30003    