apiVersion: v1 
kind: Pod
metadata: 
  name: myapp-pod
  labels:
    app: myapp 

spec:
  containers: 
  - name: myapp-cont
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
       memory: "128Mi"
       cpu: "500m"
       

